<?php

namespace Database\Seeders;

use App\Models\ExerciseBreakdown;
use Illuminate\Database\Seeder;

class ExerciseBreakdownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ExerciseBreakdown::insert([
            // lose_weight
                // 30_mins
                    [
                        'goal' => 'lose_weight', //['lose_weight', 'gain_weight', 'build_muscle', 'get_fit']
                        'how_long_time_to_workout' => '30_mins', //['30_mins', '45_mins', '1_hour', 'more_than_1_hour']
                        'exercise_category' => 'major_lift', //['major_lift', 'single_joint', 'multi_joint', 'cardio']
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '10-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // 45_mins
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '10-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-10',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-10',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // 1_hour
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '10-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '10-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '10-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'lose_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // more_than_1_hour
                [
                    'goal' => 'lose_weight',
                    'how_long_time_to_workout' => 'more_than_1_hour',
                    'exercise_category' => 'major_lift',
                    'exercise_count' => 1,
                    'sets' => '4-8',
                    'reps' => '10-15',
                    'time' => '16m',
                ],
                [
                    'goal' => 'lose_weight',
                    'how_long_time_to_workout' => 'more_than_1_hour',
                    'exercise_category' => 'single_joint',
                    'exercise_count' => 3,
                    'sets' => '4-8',
                    'reps' => '10-20',
                    'time' => '16m',
                ],
                [
                    'goal' => 'lose_weight',
                    'how_long_time_to_workout' => 'more_than_1_hour',
                    'exercise_category' => 'multi_joint',
                    'exercise_count' => 2,
                    'sets' => '4-8',
                    'reps' => '10-20',
                    'time' => '16m',
                ],
                [
                    'goal' => 'lose_weight',
                    'how_long_time_to_workout' => 'more_than_1_hour',
                    'exercise_category' => 'cardio',
                    'exercise_count' => 1,
                    'sets' => null,
                    'reps' => null,
                    'time' => '10-15m',
                ],

            // gain_weight
                // 30_mins
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-5',
                        'reps' => '3-6',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // 45_mins
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-5',
                        'reps' => '3-6',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // 1_hour
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-5',
                        'reps' => '3-6',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // more_than_1_hour
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-5',
                        'reps' => '3-6',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'gain_weight',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],


            // build_muscle
                // 30_mins
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-6',
                        'reps' => '6-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // 45_mins
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-6',
                        'reps' => '6-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // 1_hour
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-6',
                        'reps' => '6-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // more_than_1_hour
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '3-6',
                        'reps' => '6-15',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 3,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 2,
                        'sets' => '4-8',
                        'reps' => '8-20',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'build_muscle',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],




            // get_fit
                // 30_mins
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-12',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '30_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],

                // 45_mins
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-12',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 0,
                        'sets' => null,
                        'reps' => null,
                        'time' => null,
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '4-6',
                        'reps' => '10-20',
                        'time' => '15m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '45_mins',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // 1_hour
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-12',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-15',
                        'time' => '15m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-15',
                        'time' => '15m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => '1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],
                // more_than_1_hour
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'major_lift',
                        'exercise_count' => 1,
                        'sets' => '5-7',
                        'reps' => '8-12',
                        'time' => '16m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'single_joint',
                        'exercise_count' => 2,
                        'sets' => '4-6',
                        'reps' => '8-12',
                        'time' => '15m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'multi_joint',
                        'exercise_count' => 2,
                        'sets' => '4-6',
                        'reps' => '8-12',
                        'time' => '15m',
                    ],
                    [
                        'goal' => 'get_fit',
                        'how_long_time_to_workout' => 'more_than_1_hour',
                        'exercise_category' => 'cardio',
                        'exercise_count' => 1,
                        'sets' => null,
                        'reps' => null,
                        'time' => '10-15m',
                    ],




        ]);
    }
}
