version: '3'

services:
  php:
    build: .
    image: ${PROJECT_SLUG}_php
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_SLUG}_nginx
    ports:
      - "9004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - php
      
networks:
  sleep-meditation:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.24.0/24